feat: Return group info on stage commit
wireapp/openmls pull request #25
Opened 2023-01-11 14:08 UTC by augustocdias

2023-01-12 14:32 UTC, beltram requested changes

2023-01-12 14:32 UTC, beltram commented on openmls/src/group/mls_group/membership.rs
>      /// If successful, it returns a tuple of [`MlsMessageOut`]s, where the first
```suggestion
    /// If successful, it returns a triple of [`MlsMessageOut`]s, where the first
```

2023-01-12 14:32 UTC, beltram commented on openmls/src/group/mls_group/updates.rs
>      /// If successful, it returns a tuple of [`MlsMessageOut`] (containing the
```suggestion
    /// If successful, it returns a triple of [`MlsMessageOut`] (containing the
```

2023-01-17 14:09 UTC, beltram requested changes

2023-01-17 14:09 UTC, beltram commented on openmls/tests/test_external_commit.rs
> +    let msg_in = MlsMessageIn::try_from_bytes(&message.to_bytes().unwrap()).unwrap();
can't it just be `message.into()` ?

2023-01-18 09:01 UTC, augustocdias commented on openmls/tests/test_external_commit.rs
> +    let (_, _, group_info) = alice_group.self_update(backend, None).unwrap();
That is not valid. We would have to pattern match it or make a if let expression:

```
error[E0005]: refutable pattern in local binding: `(_, _, None)` not covered
   --> openmls/tests/test_external_commit.rs:165:9
    |
165 |     let (.., Some(group_info)) = alice_group.self_update(backend, None).unwrap();
    |         ^^^^^^^^^^^^^^^^^^^^^^ pattern `(_, _, None)` not covered
    |
    = note: `let` bindings require an "irrefutable pattern", like a `struct` or an `enum` with only one variant
    = note: for more information, visit https://doc.rust-lang.org/book/ch18-02-refutability.html
    = note: the matched value is of type `(openmls::prelude_test::MlsMessageOut, Option<openmls::prelude_test::MlsMessageOut>, Option<openmls::messages::GroupInfo>)`
```

2023-01-18 15:16 UTC, beltram approved these changes

2023-01-19 08:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/openmls?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/openmls?pullRequest=25) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: franziskuskiefer<br/>:white_check_mark: augustocdias<br/>:x: duesee<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/openmls?pullRequest=25) it.</sub>

2023-01-19 08:56 UTC, closed without merging